CREATE TABLE users(
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(256),
  mail VARCHAR(256),
  password VARCHAR(256)
);

CREATE TABLE todos (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  content VARCHAR(256) NOT NULL,
  status VARCHAR(256) NOT NULL,
  user_id VARCHAR(256) NOT NULL,
  deadline DATETIME NOT NULL,
  category VARCHAR(256) NOT NULL
);

ALTER TABLE todos
ADD CONSTRAINT fk_user_id
FOREIGN KEY (user_id)
REFERENCES users(id);